"""
One-time helper to move/copy short segments into a new folder.

It uses subtitle durations from the annotation JSON and matches files generated by
`prepare_segments.py` naming:
    {index:03d}_{line_id}.wav
    {index:03d}_{line_id}.lab

Default behavior: move files with duration <= max_duration.
"""

import argparse
import json
import os
import shutil


def main():
    parser = argparse.ArgumentParser(
        description="Move/copy short SOFA segments to a new folder"
    )
    parser.add_argument(
        "--annotation",
        "-a",
        required=True,
        help="Path to annotation JSON (with subtitleLines)",
    )
    parser.add_argument(
        "--source",
        "-s",
        required=True,
        help="Source folder containing segment .wav/.lab files",
    )
    parser.add_argument(
        "--target",
        "-t",
        required=True,
        help="Target folder to receive short segments",
    )
    parser.add_argument(
        "--max-duration",
        type=float,
        default=45.0,
        help="Keep/move lines whose duration <= this threshold (seconds)",
    )
    parser.add_argument(
        "--copy",
        action="store_true",
        help="Copy instead of move (default is move)",
    )
    args = parser.parse_args()

    with open(args.annotation, "r", encoding="utf-8") as f:
        data = json.load(f)

    lines = data["project"]["subtitleLines"]
    os.makedirs(args.target, exist_ok=True)

    moved_pairs = 0
    missing_pairs = 0
    skipped_long = 0

    op = shutil.copy2 if args.copy else shutil.move
    op_name = "Copied" if args.copy else "Moved"

    for i, line in enumerate(lines, start=1):
        line_id = line["id"]
        duration = float(line["endTime"]) - float(line["startTime"])
        base = f"{i:03d}_{line_id}"
        wav_name = f"{base}.wav"
        lab_name = f"{base}.lab"
        src_wav = os.path.join(args.source, wav_name)
        src_lab = os.path.join(args.source, lab_name)
        dst_wav = os.path.join(args.target, wav_name)
        dst_lab = os.path.join(args.target, lab_name)

        if duration > args.max_duration:
            skipped_long += 1
            continue

        if not (os.path.exists(src_wav) and os.path.exists(src_lab)):
            missing_pairs += 1
            print(f"[MISSING] {base} (<= {args.max_duration}s but files not found)")
            continue

        op(src_wav, dst_wav)
        op(src_lab, dst_lab)
        moved_pairs += 1
        print(f"[OK] {base} ({duration:.1f}s)")

    print()
    print(f"{op_name} pairs: {moved_pairs}")
    print(f"Skipped long lines (> {args.max_duration}s): {skipped_long}")
    print(f"Missing pairs: {missing_pairs}")
    print(f"Target folder: {args.target}")


if __name__ == "__main__":
    main()

